baseURL: '/'
title: HymnsRepo
theme: lanyon
languageCode: en-US
canonifyurls: true
pluralizelisttitles: false
footnoteReturnLinkContents: "â†©"

params:
  siteurl:      https://hymnsrepo.com/
  tagline:      A catholic hymn repository
  description:  A repository of hymns and songs used in catholic settings.
  cachebuster:  v0
  github:       https://github.com/hymnsrepo/hymnsrepo-site


disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS

sitemap:
  changefreq: monthly
  priority: 0.5

markup:
  goldmark:
    renderer:
      hardWraps: true
